### ISSUE TITLE
The README should have instructions on how to submit manual updates

### ISSUE THREAD

**Issue by paulray** [ipta/pulsar-clock-corrections#5]
For the observatories that require manual updates, I assume those should be submitted via PRs to this repo, but I can't see that process documented anywhere.

**Comment by aarchiba** [comment]
Er. Hmm. I guess PRs? What really needs to happen is me reliably keeping an eye on things; but a PR is about as easy as possible for me to merge.

**Comment by aarchiba** [comment]
The tricky part is what to do with manual updates that conflict with updates that appear in the TEMPO/TEMPO2 repositories. Right now the Nançay corrections are not being updated because the ones in the repo are smaller than the ones I have, and the code doesn't trust that they are actually updates. I'll have to examine them and untangle the situation.

If someone provides a manual update, then until the TEMPO/TEMPO2 repository updates we'll see such a conflict. If the repository updates to match what we have, then all will settle down and future updates should happen automatically. I can set the observatory to not look for automatic updates, in which case it won't get any, but the EPTA folks tell me that their official, updating, repository is the TEMPO2 one.

**Comment by paulray** [comment]
Ah, I see. So if an observatory is in Tempo2 then it should be updated via a PR to the Tempo2 repo.

**Comment by aarchiba** [comment]
Well.. the Tempo2 repo isn't necessarily responsive enough to make that effective. (Not that this one has been better!) But if they include updated clock files, we'll pick them up too.

**Comment by aarchiba** [comment]
Let me know what you think of the new README.md; I've added some documentation about how to update the clock file.

I should probably arrange for the README.md to be incorporated into the web site as well...

**Comment by paulray** [comment]
The only thing I see is that nowhere in the docs does it say what `update_clock_corrections.py` does. Even the code just says that it "updates the clock corrections" but that doesn't say what that entails or what files/directories might be modified by running it.

**Comment by aarchiba** [comment]
Er. Good point. I think that can go in the README, but it should also be in the argparse so you can do `--help`.

For the Nançay clock file (`ncyobs2obspm.clk`) it looks like the version in the TEMPO2 repository is just the first part of the version we have - that is, ours is newer. It has about 19563 measurements in it; does yours have more?

**Comment by paulray** [comment]
The one I got from Lucas should just be an extension of what is in TEMPO2

**Comment by aarchiba** [comment]
What is in this repository is also an extension of what is in TEMPO2; could it be the one you have, or newer? (`wc -l` will give an estimate of how many points it has.)

**Comment by paulray** [comment]
The PR was merged, so what is in the repo is exactly what I have

**Comment by aarchiba** [comment]
Oh! Sorry! I managed to get confused. I still need to clear up the README and website.
